<a href="https://colab.research.google.com/github/vitor-edu/Programa-de-Formacao-Big-Data-BRQ/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [207]:
import numpy as np # importando a biblioteca numpy

array = np.array([2,33,44,55,76,78]) # Criando uma matriz unidimencional. 
print(array)

[ 2 33 44 55 76 78]


In [208]:
type(array)

numpy.ndarray

In [209]:
x = np.array([1, 2, 3, 4, 5, 6], dtype = np.float64) # Chamando a função numpy criando um array com typo específico.  
print(x)
print(x.dtype)
                                           
y = np.array([1, 2, 3, 4, 5, 6], dtype = np.float32)
print(y)
print(y.dtype)

[1. 2. 3. 4. 5. 6.]
float64
[1. 2. 3. 4. 5. 6.]
float32


In [210]:
x = np.array([3.5, 5.6, 7.8, 9.5, 78.8, 56.999, 76.000, 7.8]) # Criando array com typo de dados float. 
print(x)
print(x.dtype)


[ 3.5    5.6    7.8    9.5   78.8   56.999 76.     7.8  ]
float64


In [211]:
y = x.astype(np.int) # Convertendo o typo de dado do array, para inteiro. 
print(y)
print(y.dtype)

[ 3  5  7  9 78 56 76  7]
int64


In [212]:
z = np.array([1, 3, 45, 65, 7, 8]) # Criando array com dados do tipo inteiro. 
print(z)
print(z.dtype)

[ 1  3 45 65  7  8]
int64


In [213]:
w = z.astype(np.float) # Convertendo o typo de dado do array, para float. 
print(w)
print(w.dtype)

[ 1.  3. 45. 65.  7.  8.]
float64


In [214]:
bi_dimencional = np.array([[2,4,5],[3,4,5], [2,4,6], [5,6,7], [4,5,6]]) # Criando uma matriz bidimencional. 
bi_dimencional


array([[2, 4, 5],
       [3, 4, 5],
       [2, 4, 6],
       [5, 6, 7],
       [4, 5, 6]])

In [215]:
bi_dimencional.dtype # Tipo de dados da matriz

dtype('int64')

In [218]:
c = np.empty([10,10], dtype = int) # Criando uma matriz bidimencional 10x10. 
print(c)


[[     94805802627264     140007877515088                  -4
      140007343915009                   0      94805741586272
                   31      94805802627296     140008490214144
      140008575326560]
 [    140008490206224                   0      94805802617712
                    0                   0     140007343915009
                    0        523986010138     139637976727552
        1529008357496]
 [       519691042816                 252                   0
      140007877624816     140007877531376                   0
         146028888067      94802813124609     140007877531376
                   12]
 [    140007877531424                   0        146028888067
                    1     140007877531424     140007877616400
      140007877531472                   0        146028888067
  8391086148885151745]
 [    140007877531472        120259084292     140007877531520
                    0        146028888067     140007343915009
      140007877531520      9480281312460

In [219]:
x1 = np.zeros([10,10]) # cria uma matriz 10x10 com valores zero.
x1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [220]:
e = np.ones([10,10])# Cria uma matriz de 10x10 com numero 1. 
print(e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [222]:
eye = np.eye(10) # Cria uma matriz com 10x10 formada por zeros e um traço diagonal formado pelo numero um.  
eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [226]:
g = np.random.random((10)) # Gera 10 numeros randômicos entre 0 e 1. 
g


array([0.03143043, 0.9259463 , 0.71597402, 0.97115562, 0.20630857,
       0.44780464, 0.72808023, 0.61749269, 0.64556802, 0.15490762])

In [227]:
g2= np.random.randn((10)) # Gera 10 numeros randômicos entre 0 e 1.
g2


array([-1.19491171,  1.31474348, -0.61313422, -2.49878501,  0.10499893,
        1.40540756, -0.49033613,  0.64521802, -0.8693972 ,  0.6685198 ])

In [232]:
array = np.floor(10*np.random.random((10,10))) # Criando arrays multidimencionais com valores entre 0 e 10 multiplicado pelo valor randomizado, retornando o valor absoluto através do comando floor.   
array

array([[8., 6., 4., 3., 5., 2., 9., 4., 2., 6.],
       [4., 5., 6., 0., 4., 6., 0., 5., 1., 6.],
       [6., 0., 3., 8., 4., 6., 6., 0., 9., 6.],
       [0., 8., 4., 6., 1., 5., 8., 1., 3., 2.],
       [4., 9., 3., 5., 9., 4., 5., 8., 4., 9.],
       [8., 6., 6., 9., 6., 4., 4., 9., 6., 4.],
       [3., 8., 5., 2., 6., 6., 3., 0., 3., 5.],
       [1., 7., 6., 6., 5., 3., 6., 6., 8., 8.],
       [6., 7., 9., 5., 2., 8., 8., 3., 0., 6.],
       [9., 5., 4., 7., 0., 1., 2., 4., 8., 9.]])

In [235]:
array = (10*np.random.random((10,10))) # Criando arrays multidimencionais com valores entre 0 e 10 multiplicado pelo valor randomizado.
array

array([[3.40201604, 9.92478549, 9.09268203, 3.58042561, 6.33663248,
        2.54035112, 2.48094391, 5.09418742, 2.81400217, 1.29243307],
       [7.78914459, 5.38876969, 3.33067223, 4.27350047, 3.6027924 ,
        7.07849359, 5.9099334 , 3.47635773, 4.23905174, 6.08915709],
       [6.09161887, 5.48201015, 7.32426324, 3.62400937, 2.59447874,
        5.99095065, 6.75490311, 9.31925826, 9.66454681, 3.37642055],
       [7.87987248, 4.64237028, 3.56782017, 7.64479796, 6.63226053,
        7.68324008, 4.62788675, 6.52992258, 5.28556368, 6.72785331],
       [3.87937646, 8.90201803, 2.60819618, 2.17867976, 5.23387995,
        8.63492322, 2.51145699, 1.19906722, 4.38130476, 5.08216153],
       [1.23762447, 7.97972665, 8.18053565, 3.86600388, 6.1943604 ,
        0.33352236, 5.51305306, 0.61472376, 2.68326588, 3.3112344 ],
       [6.61221338, 2.9384739 , 8.36927305, 3.97530628, 7.7213996 ,
        0.65145403, 8.94647759, 5.15137704, 6.57807981, 6.05725334],
       [4.0331297 , 3.29862484, 5.7632683

In [237]:
array_2 = np.random.default_rng(0) # Criando um array com dez valores vazios randomicamente. 
i = array_2.random(10)
i

array([0.63696169, 0.26978671, 0.04097352, 0.01652764, 0.81327024,
       0.91275558, 0.60663578, 0.72949656, 0.54362499, 0.93507242])

In [240]:
i = array_2.integers(10, size=(10, 10)) # Criando um array 10x10 com intervalo entre 0 e 10 com valores inteiros. 
i


array([[8, 1, 7, 9, 0, 3, 6, 1, 5, 6],
       [7, 9, 4, 4, 4, 9, 1, 4, 0, 4],
       [9, 6, 3, 9, 6, 9, 0, 4, 8, 7],
       [4, 4, 4, 5, 2, 7, 0, 4, 2, 7],
       [7, 7, 9, 9, 1, 1, 1, 7, 9, 9],
       [6, 9, 8, 0, 1, 8, 0, 9, 8, 9],
       [3, 1, 5, 9, 3, 8, 3, 8, 2, 4],
       [3, 2, 8, 8, 1, 9, 9, 2, 4, 5],
       [6, 4, 1, 9, 6, 0, 8, 7, 1, 6],
       [5, 0, 9, 7, 3, 0, 0, 7, 1, 5]])

In [242]:
# Função unique verifica todo o array e retorna os valores excluindo os repetidos. 
unique = np.array([11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13,13, 14, 14, 14, 14, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
unique = np.unique(unique)
unique


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [245]:
matriz_bi = np.array([[17,22,43],[27,325,14],[15,424,32], [65,24,32], [15,424,32], [15,424,32], [15,424,32], [315,24,32], [15,5624,32]]) # Cria uma matriz bidimensional. 
matriz_bi


array([[  17,   22,   43],
       [  27,  325,   14],
       [  15,  424,   32],
       [  65,   24,   32],
       [  15,  424,   32],
       [  15,  424,   32],
       [  15,  424,   32],
       [ 315,   24,   32],
       [  15, 5624,   32]])

In [250]:
matriz_bi[0][1] # Retornando um elemento da lista. 

22

In [251]:
matriz_bi[2][2] # Retornando um elemento da lista. 

32

In [253]:
matriz_bi[2][1] # Retornando um elemento da lista. 

424

In [254]:
matriz_bi.shape # Mostra o tamanho da matriz dez linhas e trêz colunas. 

(9, 3)

In [255]:
  matriz_bi.max() # Mostra o maior valor da matriz. 


5624

In [256]:
matriz_bi.min() # Mostra o menor valior da matriz. 

14

In [258]:
matriz_bi.sum()#  Mostra a soma da matriz. 

8495

In [259]:
matriz_bi.mean() # Mostra a média dos valores da matriz. 

314.6296296296296

In [261]:
matriz_bi.std() # Mostra o desvio padrão, dos valores da matriz.  

1052.2949927252707

In [266]:
array_3 = np.array([2, 4, 6, 16, 25, 36, 100, 81]) # Criando um array de inteiros. 
array_3


array([  2,   4,   6,  16,  25,  36, 100,  81])

In [268]:
np.sqrt(array_3) # Retornando os valores da raiz dos elementos do array. 

array([ 1.41421356,  2.        ,  2.44948974,  4.        ,  5.        ,
        6.        , 10.        ,  9.        ])

In [269]:
np.exp(array_3) # Retornando os valores dos expoentes dos elementos. 

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 2.68811714e+43, 1.50609731e+35])

In [286]:
#  Criando um array multidimencional. 
l = np.array([[4,5,6], [6,1,7], [7,4,7], [3,4,8], [4,5,5], [6,7,9], [4,5,5], [5,6,2],
              [3,4,3], [3,4,7], [4,5,4], [4,5,3], [4,5,2], [5,6,2], [7,8,8], [7,8,8]]) 
                        
print(l)

[[4 5 6]
 [6 1 7]
 [7 4 7]
 [3 4 8]
 [4 5 5]
 [6 7 9]
 [4 5 5]
 [5 6 2]
 [3 4 3]
 [3 4 7]
 [4 5 4]
 [4 5 3]
 [4 5 2]
 [5 6 2]
 [7 8 8]
 [7 8 8]]


In [289]:
l_linha_1 = l[0, :] # Retornando a primeira linha. 
print(l_linha_1)

[4 5 6]


In [291]:
l_linha_2 = l[1, :] # Retornando a segunda lionha inteira. 
print(l_linha_2)

[6 1 7]


In [293]:
l_linha_3 = l[2, :] # Retornando a terceira linha inteira. 
print(l_linha_3)

[7 4 7]


In [299]:
coluna_1 = l[:, 0] # retornando coluna 1. 
coluna_1


array([4, 6, 7, 3, 4, 6, 4, 5, 3, 3, 4, 4, 4, 5, 7, 7])

In [298]:
coluna_2 = l[:, 1] # Retornando coluna 2. 
coluna_2

array([5, 1, 4, 4, 5, 7, 5, 6, 4, 4, 5, 5, 5, 6, 8, 8])

In [297]:
coluna_3 = l[:, 2] # Retornando coluna 3.
coluna_3

array([6, 7, 7, 8, 5, 9, 5, 2, 3, 7, 4, 3, 2, 2, 8, 8])

In [303]:
array_4 = np.array([1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 5, 5, 7]) # Criando array com numeros inteiros. 
array_4

array([1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 5, 5, 7])

In [305]:
array_4[2] # Retorna os dados da posição 2. 

3

In [307]:
array_4[0:4] # Retorna os dados da posiçào um até a posição 4. 

array([1, 2, 3, 4])

In [309]:
array_4[1:8] # Retorna o dado da posição 2 até a posição 8. 

array([2, 3, 4, 5, 6, 3, 4])

In [311]:
array_4[-3:] # Retorna o valor apartir da antipenultima posição. 

array([5, 5, 7])

In [312]:
n = np.array([[1, 2], [3, 4]]) # criando dois arrays multidimencionais
o = np.array([[1, 1], [1, 1]])

In [314]:
result = n+o # Somando os dois arrays e guardando em uma variavel o resultado. 
result

array([[2, 3],
       [4, 5]])

In [316]:
result_2 = n*o # Multiplicando os valores do array e guardando em uma variável. 
result_2

array([[1, 2],
       [3, 4]])

In [317]:
p = np.array([[1, 2], [3, 4], [5, 6]]) # Criando um array com 3 listas
q = np.array([[2, 1]]) # Criando um array com uma lista. 


In [321]:
x = p + q # Somando o array q com uma lista com todas as listas do array p. 
x

array([[3, 3],
       [5, 5],
       [7, 7]])

In [340]:
# Criando um array do 0 ao numero 500,  usando comando reshape com parâmetros relacionado quantidades de linhas e colunas. 
r = np.arange(500).reshape((50,10)) 
r

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [339]:
# Criando um array do o ao numero 1500 usando comando reshape com parâmetros relacionado a linhas e colunas. 
r2 = np.arange(1500).reshape((30,50))
r2

array([[   0,    1,    2, ...,   47,   48,   49],
       [  50,   51,   52, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  147,  148,  149],
       ...,
       [1350, 1351, 1352, ..., 1397, 1398, 1399],
       [1400, 1401, 1402, ..., 1447, 1448, 1449],
       [1450, 1451, 1452, ..., 1497, 1498, 1499]])

In [342]:
matriz_transposta = r2.T # Função T transforma linhas em colunas e colunas em linhas. 
matriz_transposta

array([[   0,   50,  100, ..., 1350, 1400, 1450],
       [   1,   51,  101, ..., 1351, 1401, 1451],
       [   2,   52,  102, ..., 1352, 1402, 1452],
       ...,
       [  47,   97,  147, ..., 1397, 1447, 1497],
       [  48,   98,  148, ..., 1398, 1448, 1498],
       [  49,   99,  149, ..., 1399, 1449, 1499]])

In [347]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]) # Criando uma matriz multidimencional. 
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [351]:
s1 = a.T # criando uma matriz transposta, alterando o conteúdo entre linha e coluna. 
s1

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [357]:
r = np.arange(60).reshape((6,10)) # Criando um array do 0 ao 60, usando a função reshape com 6 linhas e 10 colunas.  
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [363]:
s1 = r.transpose((1,0)) # Criando um array com o comando transpose, transformando colunas em linhas e linhas em colunas.
s1

array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55],
       [ 6, 16, 26, 36, 46, 56],
       [ 7, 17, 27, 37, 47, 57],
       [ 8, 18, 28, 38, 48, 58],
       [ 9, 19, 29, 39, 49, 59]])

In [366]:
# Criando um array entre os inteiros 0 e 16, usando o comando reshape descrevendo a quantidade de blocos linhas e colunas. 
t = np.arange(16).reshape((2,2,4))  
t

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [371]:
# Criando um array entre os inteiros 0 e 500, usando o comando reshape descrevendo a quantidade de blocos linhas e colunas. 
z = np.arange(500).reshape((2,5,50)) 
z

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
          62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
          74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
          86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168,

In [373]:
u = z.transpose((1,0,2)) # ? 
u

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49],
        [250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261,
         262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
         274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
         286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297,
         298, 299]],

       [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
          62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
          74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
          86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99],
        [300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
         312, 313, 314, 315, 316, 317, 31

In [374]:
z # Chamando o array 

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
          62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
          74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
          86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168,

In [376]:
u = z.swapaxes(1,2) # Uma função que troca os eixos de lugares, foi criada duas colunas com 250 numeros inteiros em casa totalizando 500.
u

array([[[  0,  50, 100, 150, 200],
        [  1,  51, 101, 151, 201],
        [  2,  52, 102, 152, 202],
        [  3,  53, 103, 153, 203],
        [  4,  54, 104, 154, 204],
        [  5,  55, 105, 155, 205],
        [  6,  56, 106, 156, 206],
        [  7,  57, 107, 157, 207],
        [  8,  58, 108, 158, 208],
        [  9,  59, 109, 159, 209],
        [ 10,  60, 110, 160, 210],
        [ 11,  61, 111, 161, 211],
        [ 12,  62, 112, 162, 212],
        [ 13,  63, 113, 163, 213],
        [ 14,  64, 114, 164, 214],
        [ 15,  65, 115, 165, 215],
        [ 16,  66, 116, 166, 216],
        [ 17,  67, 117, 167, 217],
        [ 18,  68, 118, 168, 218],
        [ 19,  69, 119, 169, 219],
        [ 20,  70, 120, 170, 220],
        [ 21,  71, 121, 171, 221],
        [ 22,  72, 122, 172, 222],
        [ 23,  73, 123, 173, 223],
        [ 24,  74, 124, 174, 224],
        [ 25,  75, 125, 175, 225],
        [ 26,  76, 126, 176, 226],
        [ 27,  77, 127, 177, 227],
        [ 28,  78, 1

In [383]:
v = np.random.randn(4,4) # Criando um array 4x4 inicalizando com valores aleatórios negativos. 
v

array([[-0.92889233,  0.54769416,  0.13112469,  0.41173053],
       [-0.2141063 , -0.49456966,  0.86166411, -1.57620126],
       [ 0.83496065, -0.98562333,  1.99218164, -0.92177041],
       [-0.18571213,  1.6602419 , -0.27357082,  0.67399038]])

In [385]:
x = (v > 0) # Criando um array com uma condição e retornando verdadeiro ou falso para os valores.  
x
 

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True, False,  True, False],
       [False,  True, False,  True]])

In [388]:
z = np.where(x > 0, 1, -1) # Criando um array com uma condição retornando 1 para true e -1 para false. 
z

array([[-1,  1,  1,  1],
       [-1, -1,  1, -1],
       [ 1, -1,  1, -1],
       [-1,  1, -1,  1]])