<a href="https://colab.research.google.com/github/vitor-edu/Programa-de-Formacao-Big-Data-BRQ/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [207]:
import numpy as np # importando a biblioteca numpy

array = np.array([2,33,44,55,76,78]) # Criando uma matriz unidimencional. 
print(array)

[ 2 33 44 55 76 78]


In [208]:
type(array)

numpy.ndarray

In [209]:
x = np.array([1, 2, 3, 4, 5, 6], dtype = np.float64) # Chamando a função numpy criando um array com typo específico.  
print(x)
print(x.dtype)
                                           
y = np.array([1, 2, 3, 4, 5, 6], dtype = np.float32)
print(y)
print(y.dtype)

[1. 2. 3. 4. 5. 6.]
float64
[1. 2. 3. 4. 5. 6.]
float32


In [210]:
x = np.array([3.5, 5.6, 7.8, 9.5, 78.8, 56.999, 76.000, 7.8]) # Criando array com typo de dados float. 
print(x)
print(x.dtype)


[ 3.5    5.6    7.8    9.5   78.8   56.999 76.     7.8  ]
float64


In [211]:
y = x.astype(np.int) # Convertendo o typo de dado do array, para inteiro. 
print(y)
print(y.dtype)

[ 3  5  7  9 78 56 76  7]
int64


In [212]:
z = np.array([1, 3, 45, 65, 7, 8]) # Criando array com dados do tipo inteiro. 
print(z)
print(z.dtype)

[ 1  3 45 65  7  8]
int64


In [213]:
w = z.astype(np.float) # Convertendo o typo de dado do array, para float. 
print(w)
print(w.dtype)

[ 1.  3. 45. 65.  7.  8.]
float64


In [214]:
bi_dimencional = np.array([[2,4,5],[3,4,5], [2,4,6], [5,6,7], [4,5,6]]) # Criando uma matriz bidimencional. 
bi_dimencional


array([[2, 4, 5],
       [3, 4, 5],
       [2, 4, 6],
       [5, 6, 7],
       [4, 5, 6]])

In [215]:
bi_dimencional.dtype # Tipo de dados da matriz

dtype('int64')

In [218]:
c = np.empty([10,10], dtype = int) # Criando uma matriz bidimencional 10x10. 
print(c)


[[     94805802627264     140007877515088                  -4
      140007343915009                   0      94805741586272
                   31      94805802627296     140008490214144
      140008575326560]
 [    140008490206224                   0      94805802617712
                    0                   0     140007343915009
                    0        523986010138     139637976727552
        1529008357496]
 [       519691042816                 252                   0
      140007877624816     140007877531376                   0
         146028888067      94802813124609     140007877531376
                   12]
 [    140007877531424                   0        146028888067
                    1     140007877531424     140007877616400
      140007877531472                   0        146028888067
  8391086148885151745]
 [    140007877531472        120259084292     140007877531520
                    0        146028888067     140007343915009
      140007877531520      9480281312460

In [219]:
x1 = np.zeros([10,10]) # cria uma matriz 10x10 com valores zero.
x1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [220]:
e = np.ones([10,10])# Cria uma matriz de 10x10 com numero 1. 
print(e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [222]:
eye = np.eye(10) # Cria uma matriz com 10x10 formada por zeros e um traço diagonal formado pelo numero um.  
eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [226]:
g = np.random.random((10)) # Gera 10 numeros randômicos entre 0 e 1. 
g


array([0.03143043, 0.9259463 , 0.71597402, 0.97115562, 0.20630857,
       0.44780464, 0.72808023, 0.61749269, 0.64556802, 0.15490762])

In [227]:
g2= np.random.randn((10)) # Gera 10 numeros randômicos entre 0 e 1.
g2


array([-1.19491171,  1.31474348, -0.61313422, -2.49878501,  0.10499893,
        1.40540756, -0.49033613,  0.64521802, -0.8693972 ,  0.6685198 ])

In [232]:
array = np.floor(10*np.random.random((10,10))) # Criando arrays multidimencionais com valores entre 0 e 10 multiplicado pelo valor randomizado, retornando o valor absoluto através do comando floor.   
array

array([[8., 6., 4., 3., 5., 2., 9., 4., 2., 6.],
       [4., 5., 6., 0., 4., 6., 0., 5., 1., 6.],
       [6., 0., 3., 8., 4., 6., 6., 0., 9., 6.],
       [0., 8., 4., 6., 1., 5., 8., 1., 3., 2.],
       [4., 9., 3., 5., 9., 4., 5., 8., 4., 9.],
       [8., 6., 6., 9., 6., 4., 4., 9., 6., 4.],
       [3., 8., 5., 2., 6., 6., 3., 0., 3., 5.],
       [1., 7., 6., 6., 5., 3., 6., 6., 8., 8.],
       [6., 7., 9., 5., 2., 8., 8., 3., 0., 6.],
       [9., 5., 4., 7., 0., 1., 2., 4., 8., 9.]])

In [235]:
array = (10*np.random.random((10,10))) # Criando arrays multidimencionais com valores entre 0 e 10 multiplicado pelo valor randomizado.
array

array([[3.40201604, 9.92478549, 9.09268203, 3.58042561, 6.33663248,
        2.54035112, 2.48094391, 5.09418742, 2.81400217, 1.29243307],
       [7.78914459, 5.38876969, 3.33067223, 4.27350047, 3.6027924 ,
        7.07849359, 5.9099334 , 3.47635773, 4.23905174, 6.08915709],
       [6.09161887, 5.48201015, 7.32426324, 3.62400937, 2.59447874,
        5.99095065, 6.75490311, 9.31925826, 9.66454681, 3.37642055],
       [7.87987248, 4.64237028, 3.56782017, 7.64479796, 6.63226053,
        7.68324008, 4.62788675, 6.52992258, 5.28556368, 6.72785331],
       [3.87937646, 8.90201803, 2.60819618, 2.17867976, 5.23387995,
        8.63492322, 2.51145699, 1.19906722, 4.38130476, 5.08216153],
       [1.23762447, 7.97972665, 8.18053565, 3.86600388, 6.1943604 ,
        0.33352236, 5.51305306, 0.61472376, 2.68326588, 3.3112344 ],
       [6.61221338, 2.9384739 , 8.36927305, 3.97530628, 7.7213996 ,
        0.65145403, 8.94647759, 5.15137704, 6.57807981, 6.05725334],
       [4.0331297 , 3.29862484, 5.7632683

In [237]:
array_2 = np.random.default_rng(0) # Criando um array com dez valores vazios randomicamente. 
i = array_2.random(10)
i

array([0.63696169, 0.26978671, 0.04097352, 0.01652764, 0.81327024,
       0.91275558, 0.60663578, 0.72949656, 0.54362499, 0.93507242])

In [240]:
i = array_2.integers(10, size=(10, 10)) # Criando um array 10x10 com intervalo entre 0 e 10 com valores inteiros. 
i


array([[8, 1, 7, 9, 0, 3, 6, 1, 5, 6],
       [7, 9, 4, 4, 4, 9, 1, 4, 0, 4],
       [9, 6, 3, 9, 6, 9, 0, 4, 8, 7],
       [4, 4, 4, 5, 2, 7, 0, 4, 2, 7],
       [7, 7, 9, 9, 1, 1, 1, 7, 9, 9],
       [6, 9, 8, 0, 1, 8, 0, 9, 8, 9],
       [3, 1, 5, 9, 3, 8, 3, 8, 2, 4],
       [3, 2, 8, 8, 1, 9, 9, 2, 4, 5],
       [6, 4, 1, 9, 6, 0, 8, 7, 1, 6],
       [5, 0, 9, 7, 3, 0, 0, 7, 1, 5]])

In [242]:
# Função unique verifica todo o array e retorna os valores excluindo os repetidos. 
unique = np.array([11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13,13, 14, 14, 14, 14, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
unique = np.unique(unique)
unique


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [245]:
matriz_bi = np.array([[17,22,43],[27,325,14],[15,424,32], [65,24,32], [15,424,32], [15,424,32], [15,424,32], [315,24,32], [15,5624,32]]) # Cria uma matriz bidimensional. 
matriz_bi


array([[  17,   22,   43],
       [  27,  325,   14],
       [  15,  424,   32],
       [  65,   24,   32],
       [  15,  424,   32],
       [  15,  424,   32],
       [  15,  424,   32],
       [ 315,   24,   32],
       [  15, 5624,   32]])

In [250]:
matriz_bi[0][1] # Retornando um elemento da lista. 

22

In [251]:
matriz_bi[2][2] # Retornando um elemento da lista. 

32

In [253]:
matriz_bi[2][1] # Retornando um elemento da lista. 

424

In [254]:
matriz_bi.shape # Mostra o tamanho da matriz dez linhas e trêz colunas. 

(9, 3)

In [255]:
  matriz_bi.max() # Mostra o maior valor da matriz. 


5624

In [256]:
matriz_bi.min() # Mostra o menor valior da matriz. 

14

In [258]:
matriz_bi.sum()#  Mostra a soma da matriz. 

8495

In [259]:
matriz_bi.mean() # Mostra a média dos valores da matriz. 

314.6296296296296

In [261]:
matriz_bi.std() # Mostra o desvio padrão, dos valores da matriz.  

1052.2949927252707

In [266]:
array_3 = np.array([2, 4, 6, 16, 25, 36, 100, 81]) # Criando um array de inteiros. 
array_3


array([  2,   4,   6,  16,  25,  36, 100,  81])

In [268]:
np.sqrt(array_3) # Retornando os valores da raiz dos elementos do array. 

array([ 1.41421356,  2.        ,  2.44948974,  4.        ,  5.        ,
        6.        , 10.        ,  9.        ])

In [269]:
np.exp(array_3) # Retornando os valores dos expoentes dos elementos. 

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 2.68811714e+43, 1.50609731e+35])

In [272]:
#  Criando um array multidimencional. 
l = np.array([[4, 5], [6, 1], [7, 4], [3,4], [4,5], [6,7], [4,5], [5,6],
              [3,4], [3,4], [4,5], [4,5], [4,5], [5,6], [7,8], [7,8], 
              [8,96,7], [6,7], [6,7], [6,7], [4,5]])
          
l

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  after removing the cwd from sys.path.


array([list([4, 5]), list([6, 1]), list([7, 4]), list([3, 4]),
       list([4, 5]), list([6, 7]), list([4, 5]), list([5, 6]),
       list([3, 4]), list([3, 4]), list([4, 5]), list([4, 5]),
       list([4, 5]), list([5, 6]), list([7, 8]), list([7, 8]),
       list([8, 96, 7]), list([6, 7]), list([6, 7]), list([6, 7]),
       list([4, 5])], dtype=object)

In [273]:
linha_1 = l[0:1]
linha_001