<a href="https://colab.research.google.com/github/vitor-edu/Programa-de-Formacao-Big-Data-BRQ/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [207]:
import numpy as np # importando a biblioteca numpy

array = np.array([2,33,44,55,76,78]) # Criando uma matriz unidimencional. 
print(array)

[ 2 33 44 55 76 78]


In [208]:
type(array)

numpy.ndarray

In [209]:
x = np.array([1, 2, 3, 4, 5, 6], dtype = np.float64) # Chamando a função numpy criando um array com typo específico.  
print(x)
print(x.dtype)
                                           
y = np.array([1, 2, 3, 4, 5, 6], dtype = np.float32)
print(y)
print(y.dtype)

[1. 2. 3. 4. 5. 6.]
float64
[1. 2. 3. 4. 5. 6.]
float32


In [210]:
x = np.array([3.5, 5.6, 7.8, 9.5, 78.8, 56.999, 76.000, 7.8]) # Criando array com typo de dados float. 
print(x)
print(x.dtype)


[ 3.5    5.6    7.8    9.5   78.8   56.999 76.     7.8  ]
float64


In [211]:
y = x.astype(np.int) # Convertendo o typo de dado do array, para inteiro. 
print(y)
print(y.dtype)

[ 3  5  7  9 78 56 76  7]
int64


In [212]:
z = np.array([1, 3, 45, 65, 7, 8]) # Criando array com dados do tipo inteiro. 
print(z)
print(z.dtype)

[ 1  3 45 65  7  8]
int64


In [213]:
w = z.astype(np.float) # Convertendo o typo de dado do array, para float. 
print(w)
print(w.dtype)

[ 1.  3. 45. 65.  7.  8.]
float64


In [214]:
bi_dimencional = np.array([[2,4,5],[3,4,5], [2,4,6], [5,6,7], [4,5,6]]) # Criando uma matriz bidimencional. 
bi_dimencional


array([[2, 4, 5],
       [3, 4, 5],
       [2, 4, 6],
       [5, 6, 7],
       [4, 5, 6]])

In [215]:
bi_dimencional.dtype # Tipo de dados da matriz

dtype('int64')

In [218]:
c = np.empty([10,10], dtype = int) # Criando uma matriz bidimencional 10x10. 
print(c)


[[     94805802627264     140007877515088                  -4
      140007343915009                   0      94805741586272
                   31      94805802627296     140008490214144
      140008575326560]
 [    140008490206224                   0      94805802617712
                    0                   0     140007343915009
                    0        523986010138     139637976727552
        1529008357496]
 [       519691042816                 252                   0
      140007877624816     140007877531376                   0
         146028888067      94802813124609     140007877531376
                   12]
 [    140007877531424                   0        146028888067
                    1     140007877531424     140007877616400
      140007877531472                   0        146028888067
  8391086148885151745]
 [    140007877531472        120259084292     140007877531520
                    0        146028888067     140007343915009
      140007877531520      9480281312460

In [219]:
x1 = np.zeros([10,10]) # cria uma matriz 10x10 com valores zero.
x1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [220]:
e = np.ones([10,10])# Cria uma matriz de 10x10 com numero 1. 
print(e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [222]:
eye = np.eye(10) # Cria uma matriz com 10x10 formada por zeros e um traço diagonal formado pelo numero um.  
eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [226]:
g = np.random.random((10)) # Gera 10 numeros randômicos entre 0 e 1. 
g


array([0.03143043, 0.9259463 , 0.71597402, 0.97115562, 0.20630857,
       0.44780464, 0.72808023, 0.61749269, 0.64556802, 0.15490762])

In [227]:
g2= np.random.randn((10)) # Gera 10 numeros randômicos entre 0 e 1.
g2


array([-1.19491171,  1.31474348, -0.61313422, -2.49878501,  0.10499893,
        1.40540756, -0.49033613,  0.64521802, -0.8693972 ,  0.6685198 ])

In [232]:
array = np.floor(10*np.random.random((10,10))) # Criando arrays multidimencionais com valores entre 0 e 10 multiplicado pelo valor randomizado, retornando o valor absoluto através do comando floor.   
array

array([[8., 6., 4., 3., 5., 2., 9., 4., 2., 6.],
       [4., 5., 6., 0., 4., 6., 0., 5., 1., 6.],
       [6., 0., 3., 8., 4., 6., 6., 0., 9., 6.],
       [0., 8., 4., 6., 1., 5., 8., 1., 3., 2.],
       [4., 9., 3., 5., 9., 4., 5., 8., 4., 9.],
       [8., 6., 6., 9., 6., 4., 4., 9., 6., 4.],
       [3., 8., 5., 2., 6., 6., 3., 0., 3., 5.],
       [1., 7., 6., 6., 5., 3., 6., 6., 8., 8.],
       [6., 7., 9., 5., 2., 8., 8., 3., 0., 6.],
       [9., 5., 4., 7., 0., 1., 2., 4., 8., 9.]])

In [234]:
array = (10*np.random.random((10,10)))
array

array([[3.71172164e+00, 9.59808515e+00, 5.55587795e+00, 7.12807464e+00,
        6.83504667e+00, 2.67567766e+00, 1.87079114e-01, 9.39369380e+00,
        3.80587411e+00, 2.64799575e+00],
       [5.97169330e+00, 2.84801019e-01, 8.40169242e+00, 2.04643996e-01,
        3.77359752e-03, 9.42499438e+00, 7.15465810e+00, 2.92456267e+00,
        1.61262071e+00, 8.57412132e+00],
       [8.28720929e+00, 7.54634753e+00, 4.69697822e+00, 2.68416640e+00,
        5.82298673e+00, 9.41351108e+00, 1.70946462e+00, 3.93422881e+00,
        7.28607674e+00, 2.79261616e+00],
       [8.85048996e+00, 9.02909696e-01, 5.03772986e+00, 8.14129421e+00,
        2.74150833e+00, 6.06791398e+00, 6.75055123e+00, 7.89207224e+00,
        4.40803974e+00, 7.88395767e+00],
       [1.83808120e+00, 2.86534165e+00, 6.59531929e+00, 9.43541766e+00,
        4.74326746e+00, 5.90622397e-01, 5.17336655e+00, 1.68513654e+00,
        3.93689600e+00, 1.93920084e+00],
       [1.00953699e+00, 6.97353326e+00, 4.66983727e+00, 4.09825696e+00,
   

In [ ]:
# teste