<a href="https://colab.research.google.com/github/vitor-edu/Programa-de-Formacao-Big-Data-BRQ/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd  # importar a biblioteca pandas

s1 = pd.Series([2,3,4,5,6,54,55,67,88]) # Comando series cria um index
s1

0     2
1     3
2     4
3     5
4     6
5    54
6    55
7    67
8    88
dtype: int64

In [4]:
import numpy as np # importando a biblioteca numpy

array = np.array([2,33,44,55,76,78]) # Criando uma matriz unidimencional. 
print(array)

[ 2 33 44 55 76 78]


In [16]:
type(array)

numpy.ndarray

In [23]:
x = np.array([1, 2, 3, 4, 5, 6], dtype = np.float64) # Chamando a função numpy criando um array com typo específico.  
print(x)
print(x.dtype)
                                           
y = np.array([1, 2, 3, 4, 5, 6], dtype = np.float32)
print(y)
print(y.dtype)

[1. 2. 3. 4. 5. 6.]
float64
[1. 2. 3. 4. 5. 6.]
float32


In [25]:
x = np.array([3.5, 5.6, 7.8, 9.5, 78.8, 56.999, 76.000, 7.8]) # Criando array com typo de dados float. 
print(x)
print(x.dtype)


[ 3.5    5.6    7.8    9.5   78.8   56.999 76.     7.8  ]
float64


In [28]:
y = x.astype(np.int) # Convertendo o typo de dado do array, para inteiro. 
print(y)
print(y.dtype)

[ 3  5  7  9 78 56 76  7]
int64


In [31]:
z = np.array([1, 3, 45, 65, 7, 8]) # Criando array com dados do tipo inteiro. 
print(z)
print(z.dtype)

[ 1  3 45 65  7  8]
int64


In [34]:
w = z.astype(np.float) # Convertendo o typo de dado do array, para float. 
print(w)
print(w.dtype)

[ 1.  3. 45. 65.  7.  8.]
float64


In [43]:
bi_dimencional = np.array([[2,4,5],[3,4,5], [2,4,6], [5,6,7], [4,5,6]]) # Criando uma matriz bidimencional. 
bi_dimencional


array([[2, 4, 5],
       [3, 4, 5],
       [2, 4, 6],
       [5, 6, 7],
       [4, 5, 6]])

In [45]:
bi_dimencional.dtype # tipo de dados da matriz

dtype('int64')